"""Rollout schema, per TECHNICAL_SPEC.md Section 5.1-5.3.

A Rollout is the single unit of data in WorldGap: one timestamped sequence of
states for one task instance, regardless of modality. Perception rollouts hold
landmark sequences; actuation rollouts hold commanded-pressure/response
sequences. Everything downstream of this schema is modality-agnostic.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal

import numpy as np

Modality = Literal["perception", "actuation"]
Source = Literal["real", "sim", "synthetic"]

# --- Temporal provenance (spec 5.1, extension; see docs/temporal_provenance.md)
#
# `source` says where the VALUES came from. This says where the TIME AXIS came
# from, which is a separate question and the one that was silently unanswered
# in releases up to 0.1.0.
#
# The motivating bug: HaGRID is, by its own name, an *image* dataset -- ~554k
# unrelated stills from different subjects, scenes and sessions. Globbing a
# gesture folder and handing the file list to `extract_rollout_from_frames()`
# produces an object that is shaped exactly like a trajectory and is not one.
# Every temporal claim downstream (the JEPA predictor learning dynamics, tremor
# as an 8 Hz oscillation, dropout as a run of missed frames) would then be
# computed over an ordering that is an artifact of `sorted(glob())`. Nothing in
# the code would complain; the numbers would just be meaningless.
#
# So every Rollout carries its time axis's provenance, and code that depends on
# real temporal structure checks it.
TemporalProvenance = Literal[
    "video", "static_pose", "synthetic_from_static", "simulated", "quasi_static_sweep"
]

TEMPORAL_PROVENANCE_KEY = "temporal_provenance"

TEMPORAL_PROVENANCE_MEANING: dict[str, str] = {
    "video": (
        "Frames are consecutive samples of one continuous recording at the "
        "stated frame_rate_hz. The only provenance for which the JEPA temporal "
        "objective and time-domain perturbations (tremor frequency, dropout "
        "runs) mean what they say."
    ),
    "static_pose": (
        "A single held pose captured as one image; T == 1. There is no time "
        "axis. Usable for frame-level distribution comparison only -- NOT for "
        "world-model training, which has no future window to predict."
    ),
    "synthetic_from_static": (
        "A trajectory constructed from a static pose by applying a known "
        "motion/perturbation model. Real pose, invented dynamics. Legitimate "
        "for calibrating or unit-testing the perturbation models themselves; "
        "never a substitute for measured motion, and any result from it is a "
        "statement about the perturbation model, not about the world."
    ),
    "simulated": (
        "Generated by a simulator or an analytic model (e.g. the V2 PGM "
        "actuator baseline). Time axis is real within the model's own terms."
    ),
    "quasi_static_sweep": (
        "Ordering is a monotonic sweep of an independent variable (applied "
        "load, commanded pressure) in a quasi-static experiment, where each "
        "point was genuinely recorded after the one before it. Real sequential "
        "structure -- but the axis is the swept variable, not wall-clock time, "
        "so `frame_rate_hz` is nominal and any result expressed in Hz or "
        "seconds is meaningless. Ogawa 2017's Figure 4(a) load sweeps are this."
    ),
}

#: Provenances whose ordering reflects genuinely sequential observation, and on
#: which a next-window predictor is therefore learning something real.
TEMPORALLY_ORDERED_PROVENANCES = frozenset({"video", "simulated", "quasi_static_sweep"})

#: Subset of the above whose axis is real elapsed time. `quasi_static_sweep` is
#: deliberately excluded: its points are ordered but not clocked, so anything
#: reported in seconds or Hz (a tremor frequency, a dropout run length) would be
#: a unit error dressed up as a measurement.
WALL_CLOCK_PROVENANCES = frozenset({"video", "simulated"})

# Fixed feature-index layout for perception rollouts (spec 5.1.1).
# This constant is the single source of truth for "which column is what" —
# never rely on positional convention elsewhere in the codebase.
PERCEPTION_FEATURE_LAYOUT = {
    "pose": {"start": 0, "n_landmarks": 33, "dims": ("x", "y", "z", "visibility")},
    "left_hand": {"start": 132, "n_landmarks": 21, "dims": ("x", "y", "z")},
    "right_hand": {"start": 195, "n_landmarks": 21, "dims": ("x", "y", "z")},
}
PERCEPTION_STATE_DIM = 33 * 4 + 21 * 3 + 21 * 3  # 258


def perception_position_channel_mask() -> np.ndarray:
    """Boolean mask, shape (PERCEPTION_STATE_DIM,), True for spatial (x/y/z)
    channels and False for the pose block's `visibility` channel.

    Derived purely from PERCEPTION_FEATURE_LAYOUT so it stays correct if the
    layout ever changes. Purely-spatial synthetic perturbations (tremor,
    reduced range of motion) MUST use this to avoid injecting noise into
    MediaPipe's own confidence/visibility signal — a landmark's visibility
    score isn't a "position" and jittering it silently changes what
    validation-harness ground truth (spec 8.1) would later measure.
    """
    mask = np.zeros(PERCEPTION_STATE_DIM, dtype=bool)
    for group in PERCEPTION_FEATURE_LAYOUT.values():
        start = group["start"]
        dims = group["dims"]
        n_dims = len(dims)
        for landmark_idx in range(group["n_landmarks"]):
            for dim_idx, dim_name in enumerate(dims):
                if dim_name != "visibility":
                    mask[start + landmark_idx * n_dims + dim_idx] = True
    return mask


PERCEPTION_POSITION_CHANNEL_MASK = perception_position_channel_mask()


@dataclass
class Rollout:
    modality: Modality
    source: Source
    condition: dict[str, Any]
    frame_rate_hz: float
    states: np.ndarray  # shape (T, D)
    presence_mask: np.ndarray  # shape (T, K) — see note below
    timestamps_ms: np.ndarray  # shape (T,)
    metadata: dict[str, Any] = field(default_factory=dict)
    rollout_id: str | None = None

    def __post_init__(self) -> None:
        if self.states.ndim != 2:
            raise ValueError(f"states must be 2D (T, D), got shape {self.states.shape}")
        if self.presence_mask.ndim != 2:
            raise ValueError(
                f"presence_mask must be 2D (T, K), got shape {self.presence_mask.shape}"
            )
        if self.states.shape[0] != self.presence_mask.shape[0]:
            raise ValueError(
                "states and presence_mask must have the same number of timesteps: "
                f"{self.states.shape[0]} vs {self.presence_mask.shape[0]}"
            )
        if self.timestamps_ms.shape[0] != self.states.shape[0]:
            raise ValueError("timestamps_ms length must match states' timestep count")
        if self.rollout_id is None:
            self.rollout_id = self._compute_id()

        declared = self.metadata.get(TEMPORAL_PROVENANCE_KEY)
        if declared is not None and declared not in TEMPORAL_PROVENANCE_MEANING:
            raise ValueError(
                f"metadata[{TEMPORAL_PROVENANCE_KEY!r}]={declared!r} is not one of "
                f"{sorted(TEMPORAL_PROVENANCE_MEANING)}"
            )
        if declared == "static_pose" and self.states.shape[0] != 1:
            raise ValueError(
                f"temporal_provenance='static_pose' means one captured pose, so T must "
                f"be 1; got T={self.states.shape[0]}. If you stacked several stills "
                "into one array, that is the pseudo-trajectory this field exists to "
                "prevent -- see docs/temporal_provenance.md."
            )

    # -- Temporal provenance -------------------------------------------------

    @property
    def temporal_provenance(self) -> str | None:
        """Where this rollout's TIME AXIS came from, or None if undeclared.

        None means "written before this field existed, or by a caller that did
        not say". It is deliberately not defaulted to `"video"`: silently
        assuming real temporal structure is the exact failure this field was
        added to stop.
        """
        return self.metadata.get(TEMPORAL_PROVENANCE_KEY)

    @property
    def has_ordered_time_axis(self) -> bool:
        """True only when the frame ordering reflects real sequential
        observation. Undeclared provenance returns False -- unknown is treated
        as unsafe, not as fine.
        """
        return self.temporal_provenance in TEMPORALLY_ORDERED_PROVENANCES

    def _compute_id(self) -> str:
        """Content hash so rollout_id is stable across reruns (spec 5.1: 'content-hashed,
        stable across reruns'), not a random uuid.
        """
        h = hashlib.sha256()
        h.update(self.states.tobytes())
        h.update(json.dumps(self.condition, sort_keys=True).encode())
        h.update(self.modality.encode())
        return h.hexdigest()[:16]

    # -- I/O -----------------------------------------------------------------

    def save(self, processed_dir: Path) -> Path:
        """Writes one .npz per rollout, per spec 5.3 storage layout."""
        out_dir = processed_dir / self.modality
        out_dir.mkdir(parents=True, exist_ok=True)
        path = out_dir / f"{self.rollout_id}.npz"
        np.savez_compressed(
            path,
            states=self.states,
            presence_mask=self.presence_mask,
            timestamps_ms=self.timestamps_ms,
        )
        return path

    @classmethod
    def load(
        cls,
        path: Path,
        modality: Modality,
        source: Source,
        condition: dict[str, Any],
        frame_rate_hz: float,
        metadata: dict[str, Any] | None = None,
    ) -> Rollout:
        npz = np.load(path)
        return cls(
            modality=modality,
            source=source,
            condition=condition,
            frame_rate_hz=frame_rate_hz,
            states=npz["states"],
            presence_mask=npz["presence_mask"],
            timestamps_ms=npz["timestamps_ms"],
            metadata=metadata or {},
            rollout_id=path.stem,
        )


def validate_perception_rollout(rollout: Rollout) -> None:
    """Sanity-checks a perception rollout against PERCEPTION_STATE_DIM.

    Raises rather than silently accepting a malformed feature vector — a wrong
    state_dim here is exactly the kind of silent bug spec 5.1.1 warns about.
    """
    if rollout.modality != "perception":
        raise ValueError(f"expected modality='perception', got {rollout.modality!r}")
    if rollout.states.shape[1] != PERCEPTION_STATE_DIM:
        raise ValueError(
            f"perception rollout states must have D={PERCEPTION_STATE_DIM}, "
            f"got D={rollout.states.shape[1]}"
        )


def split_into_windows(
    rollout: Rollout,
    window_frames: int,
    hop_frames: int | None = None,
) -> list[Rollout]:
    """Cuts one long recording into several shorter rollouts.

    The divergence metrics estimate a mean and covariance over a *set* of
    rollouts, and their confidence rule (spec 7.3) wants n >= 5x the latent
    dimension. One two-minute clip is one sample, which is useless for that; the
    same clip cut into non-overlapping windows is many. This is the standard way
    to get an adequate n out of a manageable amount of recording.

    Honest caveat, carried in each window's metadata as `window_of`: windows cut
    from the same recording are **not independent samples**. They share a
    subject, a session, a lighting setup and a camera. Treating them as n
    independent draws will make the Frechet/MMD confidence intervals narrower
    than they deserve. Use several separate recordings as well, and read the
    resulting confidence flag as optimistic.

    `hop_frames` defaults to `window_frames` (non-overlapping). Overlapping
    windows inflate n without adding information and make the dependence worse,
    so that default is the honest one.
    """
    if window_frames < 1:
        raise ValueError(f"window_frames must be >= 1, got {window_frames}")
    hop = hop_frames if hop_frames is not None else window_frames
    if hop < 1:
        raise ValueError(f"hop_frames must be >= 1, got {hop}")

    total = rollout.states.shape[0]
    windows: list[Rollout] = []
    for start in range(0, total - window_frames + 1, hop):
        end = start + window_frames
        windows.append(
            Rollout(
                modality=rollout.modality,
                source=rollout.source,
                condition={**rollout.condition, "window_start_frame": start},
                frame_rate_hz=rollout.frame_rate_hz,
                states=rollout.states[start:end],
                presence_mask=rollout.presence_mask[start:end],
                timestamps_ms=rollout.timestamps_ms[start:end],
                metadata={
                    **rollout.metadata,
                    "window_of": rollout.rollout_id,
                    "windows_are_not_independent_samples": True,
                },
            )
        )
    return windows
